"""Email generation for meetings (meeting server side).

Generates professional meeting follow-up emails without external dependencies.
"""

from __future__ import annotations


def generate_meeting_email(
    meeting_id: str,
    meeting_title: str,
    participants: list[dict],
    transcript: str,
    summary: str = "",
    action_items: list[str] | None = None,
    decisions: list[str] | None = None,
    follow_ups: list[str] | None = None,
    risks: list[str] | None = None,
) -> dict:
    """Generate a follow-up email for a meeting."""
    action_items = action_items or []
    decisions = decisions or []
    follow_ups = follow_ups or []
    risks = risks or []

    participant_names = [
        p.get("display_name", p.get("name", "Team")) for p in participants
    ]

    if not summary:
        lines = [l.strip() for l in transcript.split("\n") if l.strip()]
        key_lines = []
        for line in lines:
            lower = line.lower()
            score = 0
            if any(
                w in lower
                for w in ["decided", "agreed", "concluded", "will", "need to", "must"]
            ):
                score += 3
            if any(w in lower for w in ["important", "critical", "key", "main"]):
                score += 2
            if "?" in line:
                score += 1
            if score > 0:
                key_lines.append(line)
        summary = (
            "\n".join(f"- {l}" for l in key_lines[:5])
            if key_lines
            else "Meeting discussed various topics."
        )

    subject = f"Meeting Summary: {meeting_title}"

    text_lines = [
        f"Subject: {subject}",
        "",
        "Hi Team,",
        "",
        f"Here is a summary of our meeting: {meeting_title}",
        "",
        f"Participants: {', '.join(participant_names)}",
        "",
        "SUMMARY",
        summary,
        "",
    ]

    if decisions:
        text_lines.append("DECISIONS MADE")
        for i, d in enumerate(decisions, 1):
            text_lines.append(f"  {i}. {d}")
        text_lines.append("")

    if action_items:
        text_lines.append("ACTION ITEMS")
        for i, a in enumerate(action_items, 1):
            text_lines.append(f"  {i}. {a}")
        text_lines.append("")

    if follow_ups:
        text_lines.append("FOLLOW-UP ITEMS")
        for i, f in enumerate(follow_ups, 1):
            text_lines.append(f"  {i}. {f}")
        text_lines.append("")

    if risks:
        text_lines.append("RISKS & CONCERNS")
        for i, r in enumerate(risks, 1):
            text_lines.append(f"  {i}. {r}")
        text_lines.append("")

    text_lines.extend(
        [
            "Please review and let me know if anything needs to be added or corrected.",
            "",
            "Best regards",
            "",
            "---",
            "Generated by ConvoPilot AI - Microtechnique",
        ]
    )

    return {
        "subject": subject,
        "body": "\n".join(text_lines),
        "recipients": [p.get("email", "") for p in participants if p.get("email")],
        "meeting_id": meeting_id,
    }
