from fastapi import APIRouter, HTTPException, Response, status

from app.services.storage.local import LocalStorageProvider, verify_local_signed_url

router = APIRouter(prefix="/storage", tags=["storage"])


@router.get("/local/{key:path}")
async def serve_local_file(key: str, exp: int, sig: str) -> Response:
    """No auth dependency — the signature (generated by LocalStorageProvider.get_signed_url,
    only reachable from an authenticated, workspace-membership-checked route) is the
    credential, same model as the guest share-link route. `{key:path}` (not plain `{key}`) is
    required because storage keys contain slashes (`workspace_id/uuid-filename`) — FastAPI's
    default path converter stops at the first `/`. Uses LocalStorageProvider directly, not the
    settings-driven factory: this route is unambiguously about local storage by its own URL,
    regardless of which provider is configured as primary."""
    if not verify_local_signed_url(key, exp, sig):
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Invalid or expired signed URL")
    try:
        content = await LocalStorageProvider().download(key)
    except Exception as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="File not found") from exc
    return Response(content=content, media_type="application/octet-stream")
